/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TransactionHistoryFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createTracker" | "getTracker" | "userTrackers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createTracker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTracker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTrackers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createTracker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTracker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTrackers",
    data: BytesLike
  ): Result;
}

export interface TransactionHistoryFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TransactionHistoryFactory;
  waitForDeployment(): Promise<this>;

  interface: TransactionHistoryFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTracker: TypedContractMethod<[], [void], "nonpayable">;

  getTracker: TypedContractMethod<[user: AddressLike], [string], "view">;

  userTrackers: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTracker"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTracker"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "userTrackers"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  filters: {};
}
